# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jekyll Boilerplate
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Jekyll Boilerplate is a simple boilerplate to kick out new Jekyll sites
  using Webpack for the asset pipeline.
tagline: >-
  A short tagline
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Seo settings
twitter:
  username: jekyllrb
  card: summary
facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234

# Social Settings
social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# Verify site ownership with search engones
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234

# Config / Keys / Etc
google_tracking_id: UA-XXXXXXXX-1

# Build settings
include: ['_pages']
permalink: /posts/:title:output_ext
future: true
incremental: true
collections_dir: collections
collections:
  demo:
    output: true
    permalink: /:collection/:name

# Navigation
nav:
  - title: Posts
    url: posts
  - title: About
    url: about
  - title: Contact
    url: contact

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Keep files
# When clobbering the site destination, keep the selected files. Useful for
# files that are not generated by jekyll; e.g. files or assets that are
# generated by your build tool. The paths are relative to the destination.
keep_files:
  - assets

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - node_modules/
  - package.json
  - README.md
  - webpack.config.js
  - assets
  - yarn.lock
  - netlify.toml
  - postcss.config.js
  - babel.config.json
  - gulpfile.js
# page_gen-dirs: false

# page_gen:
#   - data: 'blogs'
#     template: 'blogs_index'
#     dir: 'blogs'
#     name: 'title'
#     title: 'title'
